import { useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, CheckCircle2, Heart, MapPin, Package, Pencil, Plus, Trash2 } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { ProductCard, ProductVisual } from "../components/ProductCard";
import { Badge, Button, Card, EmptyState, ErrorState, Field, Input, Modal, PageHeader, Spinner } from "../components/ui";
import { useAuth } from "../core/auth/AuthProvider";
import { formatCurrency, formatDate, orderStatusLabel, refundStatusLabel, shortId } from "../core/format";
import type { Address, Order } from "../core/types";
import { accountApi, accountKeys } from "../features/account/api";
import { catalogApi, catalogKeys } from "../features/catalog/api";
import { commerceApi, commerceKeys } from "../features/commerce/api";

function useCustomerId() {
  const { session } = useAuth();
  return session.customerProfileId ?? "";
}

export function AccountOverviewPage() {
  const customerId = useCustomerId();
  const profile = useQuery({ queryKey: accountKeys.profile(customerId), queryFn: () => accountApi.profile(customerId) });
  const orders = useQuery({ queryKey: commerceKeys.orders(customerId), queryFn: () => commerceApi.orders(customerId) });
  const wishlist = useQuery({ queryKey: commerceKeys.wishlist(customerId), queryFn: () => commerceApi.wishlist(customerId) });
  return <><PageHeader eyebrow="Your space" title={profile.data ? `Hello, ${profile.data.firstName}` : "Account overview"} description="Everything tied to your current development customer profile."/><div className="overview-grid"><Link to="/account/orders" className="overview-card"><span><Package/></span><div><small>Orders</small><strong>{orders.data?.length ?? (orders.isLoading ? "…" : 0)}</strong><p>Track purchases and review details.</p></div><ArrowRight/></Link><Link to="/account/wishlist" className="overview-card"><span><Heart/></span><div><small>Saved items</small><strong>{wishlist.data?.items.length ?? (wishlist.isLoading ? "…" : 0)}</strong><p>Keep interesting products close.</p></div><ArrowRight/></Link><Link to="/account/addresses" className="overview-card"><span><MapPin/></span><div><small>Delivery</small><strong>Addresses</strong><p>Manage where your orders go.</p></div><ArrowRight/></Link></div><section className="account-section"><div className="section-heading"><div><span className="eyebrow">Latest activity</span><h2>Recent orders</h2></div><Link to="/account/orders">View all <ArrowRight/></Link></div>{orders.isLoading?<Spinner/>:orders.isError?<ErrorState error={orders.error}/>:orders.data?.length?<div className="order-list">{orders.data.slice(0,3).map(order=><OrderCard key={order.id} order={order}/>)}</div>:<EmptyState title="No orders yet" description="When you complete checkout, the persisted order will appear here." action={<Link className="button button--primary button--md" to="/products">Start shopping</Link>}/>}</section></>;
}

export function ProfilePage() {
  const customerId = useCustomerId();
  const queryClient = useQueryClient();
  const profile = useQuery({ queryKey: accountKeys.profile(customerId), queryFn: () => accountApi.profile(customerId) });
  const [values, setValues] = useState({ firstName: "", lastName: "", email: "", phone: "" });
  useEffect(()=>{ if(profile.data) setValues({ firstName:profile.data.firstName,lastName:profile.data.lastName,email:profile.data.email,phone:profile.data.phone }); },[profile.data]);
  const save = useMutation({ mutationFn: () => accountApi.updateProfile(customerId, values), onSuccess: () => queryClient.invalidateQueries({queryKey:accountKeys.profile(customerId)}) });
  if(profile.isLoading) return <Spinner/>;
  if(profile.isError) return <ErrorState error={profile.error} onRetry={()=>profile.refetch()}/>;
  return <><PageHeader eyebrow="Personal details" title="Your profile" description="This information is loaded from and saved to the customer profile API."/><Card className="form-card"><form onSubmit={(e)=>{e.preventDefault();save.mutate();}}><div className="form-grid"><Field label="First name"><Input required value={values.firstName} onChange={e=>setValues({...values,firstName:e.target.value})}/></Field><Field label="Last name"><Input required value={values.lastName} onChange={e=>setValues({...values,lastName:e.target.value})}/></Field><Field label="Email"><Input type="email" required value={values.email} onChange={e=>setValues({...values,email:e.target.value})}/></Field><Field label="Phone"><Input value={values.phone} onChange={e=>setValues({...values,phone:e.target.value})}/></Field></div>{save.error&&<div className="form-alert">{save.error.message}</div>}{save.isSuccess&&<div className="form-success"><CheckCircle2/> Profile saved.</div>}<div className="form-actions"><Button type="submit" disabled={save.isPending}>{save.isPending?"Saving…":"Save changes"}</Button></div></form></Card></>;
}

const blankAddress = { receiverName:"",phone:"",province:"",district:"",commune:"",street:"",isDefault:false };
export function AddressesPage() {
  const customerId = useCustomerId();
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: commerceKeys.addresses(customerId), queryFn:()=>commerceApi.addresses(customerId) });
  const [editing,setEditing]=useState<Address|null|"new">(null);
  const [form,setForm]=useState(blankAddress);
  const open=(address:Address|null)=>{setEditing(address??"new");setForm(address?{receiverName:address.receiverName,phone:address.phone,province:address.province,district:address.district,commune:address.commune,street:address.street,isDefault:address.isDefault}:blankAddress)};
  const mutation=useMutation({mutationFn:async()=>{if(editing==="new")await commerceApi.createAddress({customerProfileId:customerId,...form} as Omit<Address,"id"|"createdAt">);else await commerceApi.updateAddress((editing as Address).id,form)},onSuccess:()=>{queryClient.invalidateQueries({queryKey:commerceKeys.addresses(customerId)});setEditing(null)}});
  const remove=useMutation({mutationFn:(id:string)=>commerceApi.deleteAddress(id),onSuccess:()=>queryClient.invalidateQueries({queryKey:commerceKeys.addresses(customerId)})});
  return <><PageHeader eyebrow="Delivery details" title="Addresses" description="Use real persisted addresses for checkout." action={<Button onClick={()=>open(null)}><Plus/> Add address</Button>}/>{query.isLoading?<Spinner/>:query.isError?<ErrorState error={query.error} onRetry={()=>query.refetch()}/>:query.data?.length?<div className="address-grid">{query.data.map(address=><Card className="address-card" key={address.id}><div><MapPin/>{address.isDefault&&<Badge tone="success">Default</Badge>}</div><h2>{address.receiverName}</h2><p>{address.street}<br/>{address.commune}, {address.district}<br/>{address.province}</p><small>{address.phone}</small><footer><Button variant="ghost" size="sm" onClick={()=>open(address)}><Pencil/> Edit</Button><Button variant="ghost" size="sm" onClick={()=>{if(window.confirm("Delete this address?"))remove.mutate(address.id)}}><Trash2/> Delete</Button></footer></Card>)}</div>:<EmptyState title="No saved addresses" description="Add an address to prepare for checkout." action={<Button onClick={()=>open(null)}><Plus/> Add address</Button>}/>} {editing&&<Modal title={editing==="new"?"Add delivery address":"Edit delivery address"} onClose={()=>setEditing(null)}><form onSubmit={(e:FormEvent)=>{e.preventDefault();mutation.mutate()}} className="modal-form"><div className="form-grid"><Field label="Receiver name"><Input required value={form.receiverName} onChange={e=>setForm({...form,receiverName:e.target.value})}/></Field><Field label="Phone"><Input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Province"><Input required value={form.province} onChange={e=>setForm({...form,province:e.target.value})}/></Field><Field label="District"><Input required value={form.district} onChange={e=>setForm({...form,district:e.target.value})}/></Field><Field label="Commune"><Input required value={form.commune} onChange={e=>setForm({...form,commune:e.target.value})}/></Field><Field label="Street"><Input required value={form.street} onChange={e=>setForm({...form,street:e.target.value})}/></Field></div><label className="check-field"><input type="checkbox" checked={form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/> Make this my default address</label>{mutation.error&&<div className="form-alert">{mutation.error.message}</div>}<div className="form-actions"><Button type="button" variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending?"Saving…":"Save address"}</Button></div></form></Modal>}</>;
}

export function WishlistPage() {
  const customerId=useCustomerId(); const queryClient=useQueryClient();
  const query=useQuery({queryKey:commerceKeys.wishlist(customerId),queryFn:()=>commerceApi.wishlist(customerId)});
  const clear=useMutation({mutationFn:()=>commerceApi.clearWishlist(customerId),onSuccess:data=>queryClient.setQueryData(commerceKeys.wishlist(customerId),data)});
  return <><PageHeader eyebrow="Things worth another look" title="Saved items" description="Your wishlist is loaded directly from the backend." action={query.data?.items.length?<Button variant="secondary" onClick={()=>{if(window.confirm("Clear your wishlist?"))clear.mutate()}}>Clear all</Button>:undefined}/>{query.isLoading?<Spinner/>:query.isError?<ErrorState error={query.error} onRetry={()=>query.refetch()}/>:query.data?.items.length?<div className="product-grid">{query.data.items.map(item=><ProductCard key={item.id} product={item.product}/>)}</div>:<EmptyState title="Nothing saved yet" description="Tap the heart on a product to keep it here." action={<Link className="button button--primary button--md" to="/products">Explore products</Link>}/>}</>;
}

function OrderCard({order}:{order:Order}){const status=orderStatusLabel(order.status);return <Link className="order-card" to={`/account/orders/${order.id}`}><div><span className="eyebrow">Order {shortId(order.id)}</span><h3>{formatDate(order.createdAt)}</h3><p>{order.orderItems.length} {order.orderItems.length===1?"item":"items"}</p></div><div><Badge tone={order.status===5?"success":order.status===6||order.status===8?"danger":"info"}>{status}</Badge><strong>{formatCurrency(order.totalAmount)}</strong></div><ArrowRight/></Link>}
export function OrdersPage(){const id=useCustomerId();const query=useQuery({queryKey:commerceKeys.orders(id),queryFn:()=>commerceApi.orders(id)});return <><PageHeader eyebrow="Purchase history" title="Your orders" description="Statuses and totals are shown exactly as persisted by the backend."/>{query.isLoading?<Spinner/>:query.isError?<ErrorState error={query.error} onRetry={()=>query.refetch()}/>:query.data?.length?<div className="order-list">{query.data.map(order=><OrderCard key={order.id} order={order}/>)}</div>:<EmptyState title="No orders yet" description="Your checkout history will appear here." action={<Link className="button button--primary button--md" to="/products">Start shopping</Link>}/>}</>}

export function OrderDetailPage(){const {orderId=""}=useParams();const query=useQuery({queryKey:commerceKeys.order(orderId),queryFn:()=>commerceApi.order(orderId)});const productQueries=useQueries({queries:(query.data?.orderItems??[]).map(item=>({queryKey:catalogKeys.product(item.productId),queryFn:()=>catalogApi.product(item.productId)}))});if(query.isLoading)return <Spinner/>;if(query.isError)return <ErrorState error={query.error} onRetry={()=>query.refetch()}/>;if(!query.data)return null;const order=query.data;const steps=["Confirmed","Packed","Shipped","Delivered"];return <><Link className="back-link" to="/account/orders">← Back to orders</Link><PageHeader eyebrow={`Order ${shortId(order.id)}`} title={orderStatusLabel(order.status)} description={`Placed ${formatDate(order.createdAt)}`} action={<Badge tone={order.status===5?"success":order.status===6||order.status===8?"danger":"info"}>{orderStatusLabel(order.status)}</Badge>}/>{order.status>=2&&order.status<=5&&<Card className="order-timeline"><h2>Order progress</h2><div>{steps.map((step,index)=>{const stepStatus=index+2;return <div className={stepStatus<=order.status?"is-complete":""} key={step}><span>{stepStatus<=order.status?<CheckCircle2/>:index+1}</span><b>{step}</b></div>})}</div></Card>}<Card className="order-items"><h2>Items</h2>{order.orderItems.map((item,index)=><div key={item.id}><ProductVisual compact name={productQueries[index]?.data?.name??"Product"}/><div><Link to={`/products/${item.productId}`}>{productQueries[index]?.data?.name??`Product ${shortId(item.productId)}`}</Link><span>{item.quantity} × {formatCurrency(item.unitPrice)}</span></div><strong>{formatCurrency(item.totalPrice)}</strong></div>)}<footer><span>Order total</span><strong>{formatCurrency(order.totalAmount)}</strong></footer></Card>{order.note&&<Card><h2>Order note</h2><p>{order.note}</p></Card>}</>}

export function RefundsPage(){const customerId=useCustomerId();const query=useQuery({queryKey:commerceKeys.refunds(customerId),queryFn:()=>commerceApi.refunds(customerId)});return <><PageHeader eyebrow="After-purchase care" title="Refunds" description="Only genuine refund requests appear here. Declined payments remain in order history as payment failures."/>{query.isLoading?<Spinner/>:query.isError?<ErrorState error={query.error} onRetry={()=>query.refetch()}/>:query.data?.length?<div className="order-list">{query.data.map(refund=><Card className="refund-card" key={refund.id}><div><span className="eyebrow">Refund {shortId(refund.id)}</span><h3>{formatDate(refund.createdAt)}</h3><p>{refund.reason}</p></div><div><Badge tone={refund.status===4?"success":refund.status===3?"danger":"info"}>{refundStatusLabel(refund.status)}</Badge><strong>{formatCurrency(refund.amount)}</strong></div></Card>)}</div>:<EmptyState title="No refunds" description="You have no refund requests. Failed or declined payments are not refunds."/>}</>}
